# Generated by Django 5.2.8 on 2025-11-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('WEB_DEV', 'Web Development'), ('SYS_DESIGN', 'System Design'), ('TALK', 'Talk')], max_length=100)),
                ('short_summary', models.TextField()),
                ('role', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('stack', models.CharField(max_length=100)),
                ('repository', models.URLField(blank=True)),
                ('challenge', models.TextField()),
                ('key_features', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
            ],
        ),
    ]
